---
"+1": c4
"-1/": df4
"-1": d4
"+2": e4
"-2//": f4
"-2/": gf4
"-2": g4
"+3": g4
"-3///": af4
"-3//": a4
"-3/": bf4
"-3": b4
"+4": c5
"-4/": df5
"-4": d5
"+5": e5
"-5": f5
"+6": g5
"-6/": af5
"-6": a5
"-7": b5
"+7": c6
"-8": d6
"+8/": ef6
"+8": e6
"-9": f6
"+9/": gf6
"+9": g6
"-10": a6
"+10//": bf6
"+10/": b6
"+10": c7
