---
- "-1 root chord-v"
- "+1 root chord-iv"
- "-2+3 root chord-i"
- "+4 root chord-iv"
- "-4 root chord-v"
- "+6 root chord-i"
- "+7 root chord-iv"
- "-8 root chord-v"
- "+9 root chord-i"
- "+10 root chord-iv"
