---
# default value if not given on commandline
type: richter

# default value
key: c

# While listening, show comments as note or interval
comment_listen: note

# for quiz and licks
comment_quiz: holes_large

# what to display for listen when a note has been recognized
display_listen: chart_notes

# what to display for quiz and licks when a note has been recognized
display_quiz: hole
display_licks: hole

# measure frequency over slices of this duration (in secs)
time_slice: 0.1

# pitch-detection algorithm used for aubiopitch; see its man-page
pitch_detection: yinfast

# default for preferred signature: prefer flats or sharps in display ?
# Not used if specified scale itself has flat or sharp
pref_sig_def: flat

# cut off below
min_freq: 50

# cut off above
max_freq: 8000

# minimum terminal screen size
term_min_width: 75
term_min_height: 24

# play holes for one second or half ?
play_holes_fast: false
