---
# default value if not given on commandline
type: richter

# default value
key: c

# While listening, show comments as note or interval
comment_listen: note

# what to display for listen when a note has been recognized
display_listen: chart

# what to display for listen when a note has been recognized
display_quiz: note
