---
# default value if not given on commandline
type: richter

# default value
key: c

# While listening, show comments as note or interval
comment_listen: note

# what to display for listen when a note has been recognized
display_listen: chart

# what to display for quiz when a note has been recognized
display_quiz: hole

# measure frequency over slices of this duration (in secs)
time_slice: 0.1

# pitch-detection algorithm used for aubiopitch; see its man-page
pitch_detection: yinfast

# cut off below
min_freq: 50

# cur off above
max_freq: 8000

# minimum terminal screen size
term_min_width: 86
term_min_height: 30

