---
'0':
  - Tonica
  - Ton
'4':
  - maj Third
  - mT
'7':
  - per Fifth
  - pF
'12':
  - Octave
  - Oct
'16':
  - Oct + Thrd
  - O+T
'19':
  - O+F
'24':
  - 2 Octaves
  - 2O
'36':
  - 3 Octaves
  - 3O
'48':
  - 4 Octaves
  - 4O
