---
'0':
  - Tonica
  - Ton
  - first
'2':
  - flat Third
  - fT
  - third
'4':
  - maj Third
  - mT
  - third
  - fav
'6':
  - flat Fifth
  - fF
  - tritone
'7':
  - per Fifth
  - pF
  - fifth
  - fav
'9':
  - Sixth
  - Si
'10':
  - flat Seventh
  - fSe
  - fav
'12':
  - Octave
  - Oct
  - fav
'16':
  - Oct + Thrd
  - O+T
'19':
  - O+F
