---
'0':
  - Tonica
  - Ton
  - first
'4':
  - maj Third
  - mT
  - third
'7':
  - per Fifth
  - pF
  - fifth
'9':
  - Sixth
  - Si
'10':
  - flat Seventh
  - fSe
'12':
  - Octave
  - Oct
'16':
  - Oct + Thrd
  - O+T
'19':
  - O+F
