---
'0':
  - Tonica
  - Ton
  - first
'2':
  - flat Third
  - fT
  - third
  - quiz_hard
'4':
  - maj Third
  - mT
  - third
  - quiz_easy
'6':
  - flat Fifth
  - fF
  - tritone
  - quiz_hard
'7':
  - per Fifth
  - pF
  - fifth
  - quiz_easy
'9':
  - Sixth
  - Si
'10':
  - flat Seventh
  - fSe
  - quiz_easy
'12':
  - Octave
  - Oct
  - quiz_easy
'16':
  - Oct + Thrd
  - O+T
'19':
  - O+F
