#
# derived scale-file with notes before all transposing applied,
# created from config/chromatic/scale_one_with_holes.yaml
#
---
- c4
- cs4
- d4
- ds4
- e4
- f4
- fs4
- g4
- gs4
- a4
- as4
- b4
- c5
- cs5
