---
"+1": c4
"+1b": cs4
"-1": d4
"-1b": ds4
"+2": e4
"-2": f4
"+2b": f4
"-2b": fs4
"+3": g4
"+3b": gs4
"-3": a4
"-3b": as4
"-4": b4
"+4": c5
"+5": c5
"-4b": c5
"+4b": cs5
"+5b": cs5
"-5": d5
"-5b": ds5
"+6": e5
"-6": f5
"+6b": f5
"-6b": fs5
"+7": g5
"+7b": gs5
"-7": a5
"-7b": as5
"-8": b5
"+8": c6
"+9": c6
"-8b": c6
"+8b": cs6
"+9b": cs6
"-9": d6
"-9b": ds6
"+10": e6
"-10": f6
"+10b": f6
"-10b": fs6
"+11": g6
"+11b": gs6
"-11": a6
"-11b": as6
"-12": b6
"+12": c7
"+12b": cs7
"-12b": d7
