---
typical_hole: "+1"
characteristic_sets:
    blow:
    - "+1"
    - "+2"
    - "+3"
    - "+4"
    - "+5"
    - "+6"
    - "+7"
    - "+8"
    draw:
    - "-1"
    - "-2"
    - "-3"
    - "-4"
    - "-5"
    - "-6"
    - "-7"
    - "-8"
