#
# derived scale-file with notes before any transposing has been applied,
# created from config/richter/scale_mape_with_holes.yaml
#
---
- short: ma
- d3
- e3
- g3
- a3
- d4
- e4
- g4
- a4
- b4
- d5
- e5
- g5
- a5
- b5
- d6
- e6
- g6
- a6
- b6
- d7
- e7
- g7
- a7
- b7
