---
- short: A
- "+1"
- "+1b"
- "-1"
- "-1b"
- "+2"
- "-2"
- "-2b"
- "+3"
- "+3b"
- "-3"
- "-3b"
- "-4"
- "+4"
- "+4b"
- "-5"
- "-5b"
- "+6"
- "-6"
- "-6b"
- "+7"
- "+7b"
- "-7"
- "-7b"
- "-8"
- "+8"
- "+8b"
- "-9"
- "-9b"
- "+10"
- "-10"
- "-10b"
- "+11"
- "+11b"
- "-11"
- "-11b"
- "-12"
- "+12"
- "+12b"
- "-12b"
