#
# derived scale file with notes before any transposing has been applied,
# created from /home/ihm/harpwise/config/richter/scale_chord-iv_with_holes.yaml
#
---
- :short: '4'
- c4 root
- e4
- g4
- c5 root
- e5
- g5
- c6 root
- e6
- g6
- c7 root
