#
# derived scale file with notes before any transposing has been applied,
# created from /home/ihm/harpwise/config/richter/scale_chord-i_with_holes.yaml
#
---
- :short: '1'
- d4
- g4 root
- b4
- d5
- g5 root
- b5
- d6
- g6 root
