---
- short: 2
- "+1"
- "+1b"
- "-1"
- "-1b"
- "+2"
- "-2+2b"
- "-2b"
- "+3"
- "+3b"
- "-3"
- "-3b"
- "-4"
- "+45-4b"
- "+45b"
- "-5"
- "-5b"
- "+6"
- "-6+6b"
- "-6b"
- "+7"
- "+7b"
- "-7"
- "-7b"
- "-8"
- "+89-8b"
- "+89b"
